<!DOCTYPE html PUBLIC "_//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">


<script type="text/javascript">
function unhide(divID) {
var item = document.getElementById(divID);
if (item) { item.className=(item.className=='hidden')?'unhidden':'hidden'; }
}

</script>

<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0" /><meta name="apple-mobile-web-app-capable" content="yes" /><meta http-equiv="content="no-cache" />
	<title>monolytical</title>
	<link href="css01.css" media="Screen" rel="stylesheet" type="text/css" />
   	<link href="mobile.css" media="handheld, only screen and (max-width: 320px), only screen 
		 and (max-device-width: 480px)" rel="stylesheet" type="text/css" /> 
	<link href="mobile.css" media="tablet, only screen and (max-width: 768px), only screen 
		 and (max-device-width: 1024pxpx), and (-webkit-min-device-pixel-ratio: 1)" rel="stylesheet" type="text/css" /> 
</head>
<body>
<main>
<header>
<br>
<!--
<h1><a href="index.htm" style="text-decoration: none"><em>Monolytical</em></a>
</h1>
-->

<br>
<h6>
<div class="blue"><b>HANDLING EXCEPTIONS</b>  <br>
problem # &nbsp; 8.9</div>

</h6>


<div class="frame">


<ol >
<li><a class="a0">public class Test {</a> </li>
<li><a class="a1">public static void main(String []args) {</a> </li>
<li><a class="a2">int x = 1;</a> </li>
<li><a class="a2">try { </a> </li>
<li><a class="a3">for (int i = 3; i >= 0; i --) {</a> </li>
<li><a class="a4">x = x + x % i;</a> </li>
<li><a class="a3">}</a> </li>
<li><a class="a2">}  catch (Exception ex) { </a> </li>
<li><a class="a2">System.out.println(x + 1); </a> </li>
<li><a class="a2">}  catch (Throwable ex) { </a> </li>
<li><a class="a2">System.out.println(x + 2); </a> </li>
<li><a class="a2">}  catch (RuntimeException ex) { </a> </li>
<li><a class="a2">System.out.println(x + 3); </a> </li>
<li><a class="a2">}</a> </li>
<li><a class="a1">}</a> </li>
<li><a class="a0">}</a> </li>
</ol>
</div>

<br>  

<h9>
<a href="javascript:unhide('solution'); " Style="text-decoration: none"> <em>Details ...</em></a>
</h9>



<div id="solution" class="hidden">
<h2>
When multiple exceptions are caught, they must appear in order â€“ from the most
specific exception to the most general one. Since <em><b>RuntimeException</b></em> is more specific than 
<em><b>Exception</b></em>, yet <u>it appears as part of the last catch clause</u> in
this code (at line 12), this program will fail to compile.
<br>
<br>
If the exceptions in this example <em>did</em> appear in the correct order, <em>RuntimeException</em> would appear first 
(then <em>Exception</em> would appear, and then <em>Throwable</em>). Then, when the code 
executed, an 
<em><b>ArithmeticException</b></em> would be thrown after the last iteration of the 
<em>for loop</em> (due to an attempt to divide by zero). That <em>ArithmeticException</em>, since it inherits 
<em>RuntimeException</em> would be caught at line 8 (where the 
<em>RuntimeException</em> catch clause <em>would</em> be written), and the program code would be 
able to complete successfully.

<br>
<br>
<br>
<br> 
<h7><script type="text/javascript" src="Last.js"></script></h7>
</h2>
</div>

<h2>
<a href="index.htm" >Home</a>
</h2>
<br>
<br>




<!--<p class="third"><a href="contactForm.html" style="text-decoration: none"><em>
comments...</em></a></p> -->
</header>
</main>
<META HTTP-EQUIV="Pragma" CONTENT="no-cache"></body>
</html>